included:
  - zaruri
  - zaruriWidget
excluded:
  - zaruriTests
  - zaruriUITests

opt_in_rules:
  - force_unwrapping
  - empty_count
  - closure_spacing

disabled_rules:
  - trailing_whitespace
  - todo

force_unwrapping: error
file_length:
  warning: 500
  error: 700
line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
type_body_length:
  warning: 400
  error: 600
function_body_length:
  warning: 60
  error: 120
identifier_name:
  min_length: 2
  excluded: [id, x, y, z, i, j]
